---
- hosts: web
  become: true
  become_user: root
  vars:
    password: hardpassword
  tasks:
    - name: Change admin user password
      user:
        name: admin  
        password: "{{ password | password_hash('sha512') }}"

    - name: Disable other users
      user:
        name: "{{item}}"
        shell: /sbin/nologin
      loop:
        - carlos
        - mia
        - john
        - patrick
        - lisa 
        - peter
        - juan
        - chris
        - jimmy

